# yaml-language-server: $schema=https://raw.githubusercontent.com/jesseduffield/lazygit/master/schema/config.json

gui:
  nerdFontsVersion: "3"
  timeFormat: "2006-01-02"
  shortTimeFormat: "15:04:05"
git:
  parseEmoji: true
  pagers:
    - pager: delta --dark --paging=never
